# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = Departure Mono

general {
    hide_cursor = false
}


animations {
    enabled = true

    bezier = hyprlock, 0.03, 0.07, 0.5, 1.2

    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, hyprlock
    animation = fadeOut, 1, 5, hyprlock
    animation = inputFieldDots, 1, 2, hyprlock
}

background {
#	path = /home/andrew/Pictures/wallpapers/bliss_fhd.jpg
	color = rgba(0, 0, 0, 0.7)
#	blur_passes = 3
#	blur_size = 1
#	vibrancy = 0.1696
#	noise = 0.0117
#	brightness = 0.25
#	contrast = 1
}

#label {
#    text = ||
#    font_size = 18
#    color = rgba(bcd42aee)
#    position = 0%, 5%
#    halign = center
#    valign = bottom
#    onclick = playerctl play-pause
#}
#
#label {
#    text = >
#    font_size = 16
#    color = rgba(bcd42aee)
#    position = 2%, 5%
#    halign = center
#    valign = bottom
#    onclick = playerctl next
#}
#
#label {
#
#    text = <
#    font_size = 16
#    color = rgba(bcd42aee)
#    position = -2%, 5%
#    halign = center
#    valign = bottom
#    onclick = playerctl previous
#}

# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 95
    font_family = $font
    color = rgba(e6f972ee)
    position = -2%, 2%
    halign = right
    valign = bottom
}

input-field {
    monitor =
    size = 70, 70
    outline_thickness = 10
    inner_color = rgba(0, 0, 0, 0)

    outer_color = rgb(100, 100, 100)
    check_color = rgb(79, 0, 0)
    fail_color = rgb(255, 0, 0)

    font_color = rgb(C00000)
    fade_on_empty = true
    rounding = -1

    font_family = $font
    placeholder_text = woe?
    fail_text = <i>WOEMF!?!? <b>($ATTEMPTS)</b></i>
    hide_input = true

    dots_spacing = 0.3
    dots_size = 0.4

    position = 0, 6%
    halign = center
    valign = bottom
}



