$paper = /home/andrew/Pictures/wallpapers/forest.jpg

preload = $paper
splash = false
wallpaper {
    monitor = DP-2
    path = $paper
    fit_mode = cover
}
#wallpaper {
#    monitor = HDMI-A-2
#    path = $paper
#    fit_mode = cover
#}
